{% set name = "skidl" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 88478f5864cc56ea3817ce38f2d8a6b89b682cbcfa88659dc7bf7559b4e08cb5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - netlist_to_skidl = skidl.netlist_to_skidl_main:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kinparse >=0.1.0
    - python-graphviz
    - future >=0.15.0

test:
  imports:
    - skidl

about:
  home: https://github.com/xesscorp/skidl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SKiDL is a module that allows you to compactly describe the interconnection of electronic circuits and components using Python.

extra:
  recipe-maintainers:
    - hmaarrfk
