{% set name = "skidl" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 745e89edfc466735a541268e828673b5cfa8de17692e2bbc1acb5ba0d759da98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - netlist_to_skidl = skidl.netlist_to_skidl_main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - kinparse >=0.1.0
    - python-graphviz
    - future >=0.15.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - skidl

about:
  home: https://github.com/xesscorp/skidl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SKiDL is a module that allows you to compactly describe the interconnection of electronic circuits and components using Python.

extra:
  recipe-maintainers:
    - hmaarrfk
