{% set version = "2.0.1" %}

package:
  name: skidl
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/skidl/skidl-{{ version }}.tar.gz
  sha256: d3d8b74cefd85948889f6fb804507f95a72e0812ffd40a467c20f53fd9593c0d

build:
  noarch: python
  number: 0
  script:
    # sexpdata is pinned too hard
    - sed -i.bak '/sexpdata/d' setup.py
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - netlist_to_skidl = skidl.scripts.netlist_to_skidl_main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - future >=0.15.0
    - sexpdata >=1.0.0
    - kinparse >=1.2.1
    - kinet2pcb >=1.1.0
    - python-graphviz
    - deprecation

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - skidl
  commands:
    - pip check

about:
  home: https://github.com/xesscorp/skidl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SKiDL is a module that allows you to compactly describe the interconnection of electronic circuits and components using Python.

extra:
  recipe-maintainers:
    - hmaarrfk
