{% set name = "skidl" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cfd469439adfd8bfc81f0b8e5eb5be381313fc7651d8ed1facaa6dfffe56c291

build:
  noarch: python
  number: 0
  script:
    - touch HISTORY.md
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - netlist_to_skidl = skidl.netlist_to_skidl_main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - kinparse >=0.1.0
    - python-graphviz
    - future >=0.15.0
    - simp-sexp

test:
  requires:
    - python {{ python_min }}
  imports:
    - skidl

about:
  home: https://github.com/xesscorp/skidl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: SKiDL is a module that allows you to compactly describe the interconnection of electronic circuits and components using Python.

extra:
  recipe-maintainers:
    - hmaarrfk
